spring.application.name=task-management-request-handler
server.port=8080
task.service.url=http://localhost:8081


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# client config
spring.security.oauth2.client.registration.task-service-client.client-id=task-manager-service
spring.security.oauth2.client.registration.task-service-client.client-secret=task-manager-secret
spring.security.oauth2.client.registration.task-service-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.task-service-client.scope=task:internal

spring.security.oauth2.client.registration.task-service-client.provider=my-auth-server

spring.security.oauth2.client.provider.my-auth-server.issuer-uri=http://localhost:9000

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect